spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:mydb.db
spring.datasource.username=
spring.datasource.password=

server.address=localhost
server.servlet.session.cookie.secure=false

spring.mail.username=
spring.mail.password=
